import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/themeProvider";
// import { PermissionProvider } from "@/context/permissionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	icons: {
		icon: "/favicon.ico"
	},
	title: "Planner",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br" className="lollipop">
			<body className={inter.className} suppressHydrationWarning={true}>
					<Toaster richColors />
					{children}
			</body>
		</html>
	);
}
