import type { Metadata } from "next";
import { Inter, Poppins, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import { Toaster } from "@/components/ui/toaster";
// import { PermissionProvider } from "@/context/permissionContext";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-poppins",
});
const notosansjp = Noto_Sans_JP({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-notosansjp",
});

export const metadata: Metadata = {
	icons: {
		icon: "/favicon.ico"
	},
	title: "Planner",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br" className="">
			<body className={notosansjp.className} suppressHydrationWarning={true}>
				{/* <Toaster /> */}
				{children}
			</body>
		</html>
	);
}
