import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { PermissionProvider } from "@/context/permissionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  icons: {
    icon: "/favicon.ico"
  },
  title: "Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="serene">
      {/* <PermissionProvider> */}
        <body className={inter.className}>
          {children}
        </body>
      {/* </PermissionProvider> */}
    </html>
  );
}
